---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

kubernetes_list: "{{ (lookup('file', root_dir ~ '/ansible/shared_resources/inventories/' ~ target_env ~ '/kubernetes.yml') | from_yaml) }}"

arch_mapping:
  x86_64: amd64
  aarch64: arm64

ntp_server: time.aws.com

kube_config_fetch_path: /tmp/kube-config

containerd_version: 2.1.3
containerd_download_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{
  arch_mapping[ansible_architecture] }}.tar.gz

runc_version: 1.3.0
runc_download_url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.{{ arch_mapping[ansible_architecture] }}

cni_plugin_version: 1.7.1
cni_plugin_download_url: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugin_version }}/cni-plugins-linux-{{
  arch_mapping[ansible_architecture] }}-v{{ cni_plugin_version }}.tgz
