---
- name: Initialize database
  ansible.builtin.shell:
    cmd: |
      mysql -u root <<EOF
      CREATE DATABASE IF NOT EXISTS glance;
      GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ glance_password }}';
      GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ glance_password }}';
      FLUSH PRIVILEGES;
      EOF
    executable: /bin/bash
  changed_when: false

- name: Configure service
  ansible.builtin.include_tasks:
    file: configure_service.yml

- name: Install Glance package
  ansible.builtin.package:
    name: glance
    state: present

- name: Setup configuration
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Populate the image service database
  ansible.builtin.command:
    cmd: sudo -u glance glance-manage db_sync
  changed_when: false

- name: Start and enable Glance API
  ansible.builtin.service:
    name: glance-api
    state: restarted
    enabled: true
