---
- name: Install packages
  ansible.builtin.include_tasks:
    file: install_packages.yml

- name: Configure dependencies
  ansible.builtin.include_tasks:
    file: configure_dependencies.yml

- name: Start and enable MariaDB
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true

- name: Start and enable Memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
    enabled: true

- name: Start and enable Etcd
  ansible.builtin.service:
    name: etcd
    state: restarted
    enabled: true
