stages:
  - lint

python-req:
  image: python:$VERSION
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements.txt
    - source circ
    - ansible-lint --fix --config-file ./.ansible-lint ansible/* inventories/*
  parallel:
    matrix:
      - VERSION: ["3.10", "3.11", "3.12"]

ansible-sanity-test-lint:
  needs:
    - job: python-req
