---
- name: Reconfigure keystone.conf - set MySQL MariaDB connection database
  ansible.builtin.replace:
    path: /etc/keystone/keystone.conf
    regexp: "^\\[database\\](\n(.*))*\n*(#connection_parameters =).*"
    replace: "{{ lookup('ansible.builtin.template', 'database.conf.j2') }}"

- name: Reconfigure keystone.conf - set Fernet token provider
  ansible.builtin.replace:
    path: /etc/keystone/keystone.conf
    regexp: "^\\[token\\](\n(.*))*\n*(#allow_expired_window =).*"
    replace: "{{ lookup('ansible.builtin.template', 'token.conf.j2') }}"
