---
- name: Initialize database
  ansible.builtin.shell:
    cmd: |
      mysql -u root <<EOF
      CREATE DATABASE IF NOT EXISTS keystone;
      GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ keystone_password }}';
      GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ keystone_password }}';
      FLUSH PRIVILEGES;
      EOF
    executable: /bin/bash
  changed_when: false

- name: Install Keystone package
  ansible.builtin.package:
    name: keystone
    state: present

- name: Setup configuration
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Populate the identity service database
  ansible.builtin.command:
    cmd: sudo -u keystone keystone-manage db_sync
  changed_when: false

- name: Initialize Fernet key repositories
  ansible.builtin.shell:
    cmd: |
      sudo -u keystone keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      sudo -u keystone keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
    executable: /bin/bash
  changed_when: false

- name: Bootstrap the identity service
  ansible.builtin.shell:
    cmd: |
      sudo -u keystone keystone-manage bootstrap --bootstrap-password {{ os_keystone_password }} \
      --bootstrap-admin-url http://{{ controller01.hostname }}:5000/v3/ \
      --bootstrap-internal-url http://{{ controller01.hostname }}:5000/v3/ \
      --bootstrap-public-url http://{{ controller01.hostname }}:5000/v3/ \
      --bootstrap-region-id RegionOne
    executable: /bin/bash
  changed_when: false

- name: Reconfigure Apache2 configuration - add ServerName
  ansible.builtin.blockinfile:
    path: /etc/apache2/apache2.conf
    append_newline: true
    prepend_newline: true
    block: ServerName {{ controller01.hostname }}
    insertafter: EOF

- name: Set environment variables
  ansible.builtin.blockinfile:
    path: /etc/environment
    append_newline: true
    prepend_newline: true
    block: "{{ lookup('ansible.builtin.template', 'environment.j2') }}"
    insertafter: EOF

- name: Start and enable Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true

- name: Create a domain, projects, users, and roles
  ansible.builtin.include_tasks:
    file: create_identity.yml
