---
- name: Set facts
  ansible.builtin.set_fact:
    overlay_if_ip_address: "{{ compute01.mgmtnet_ip_address }}"
    provider_ip_address: "{{ compute01.provider_ip_address }}"

- name: Setup configuration
  ansible.builtin.include_role:
    name: neutron
    tasks_from: main

- name: Start and enable Nova compute
  ansible.builtin.service:
    name: nova-compute
    state: restarted
    enabled: true
