---
- name: Install Neutron package
  ansible.builtin.package:
    name: neutron-openvswitch-agent
    state: present

- name: Set facts
  ansible.builtin.set_fact:
    overlay_if_ip_address: "{{ controller01.mgmtnet_ip_address }}"

- name: Setup configuration
  ansible.builtin.include_role:
    name: neutron
    tasks_from: main

- name: Start and enable Nova compute
  ansible.builtin.service:
    name: nova-compute
    state: restarted
    enabled: true

- name: Start and enable Neutron OVS agent
  ansible.builtin.service:
    name: neutron-openvswitch-agent
    state: restarted
    enabled: true
