---
- name: Set facts
  ansible.builtin.set_fact:
    overlay_if_ip_address: "{{ node.mgmtnet_ip_address }}"
    provider_ip_address: "{{ node.provider_ip_address }}"
  vars:
    node: "{{ lookup('ansible.builtin.vars', ansible_hostname) }}"

- name: Setup configuration
  ansible.builtin.include_role:
    name: neutron
    tasks_from: main

- name: Start and enable Nova compute
  ansible.builtin.service:
    name: nova-compute
    state: restarted
    enabled: true
