---
- name: Reconfigure ml2_conf.ini - set ml2
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.template', 'ml2.conf.j2') }}"

- name: Reconfigure ml2_conf.ini - set ml2_type_flat
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2_type_flat\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.template', 'ml2_type_flat.conf.j2') }}"

- name: Reconfigure openvswitch_agent.ini - set ovs
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    regexp: "^\\[ovs\\](\n(.*))*?\n*(# From neutron.ml2.ovs.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'ovs.conf.j2') }}"
