---
- name: Reconfigure openvswitch_agent.ini - set ovs
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    regexp: "^\\[ovs\\](\n(.*))*?\n*(# From neutron.ml2.ovs.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'ovs.conf.j2') }}"

- name: Reconfigure openvswitch_agent.ini - set agent
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    regexp: "^\\[agent\\](\n(.*))*?\n*(# From neutron.ml2.ovs.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'agent.conf.j2') }}"

- name: Reconfigure openvswitch_agent.ini - set security group
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    regexp: "^\\[securitygroup\\](\n(.*))*?\n*(# From neutron.ml2.ovs.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'securitygroup.conf.j2') }}"
