---
- name: Initialize database
  ansible.builtin.shell:
    cmd: |
      mysql -u root <<EOF
      CREATE DATABASE IF NOT EXISTS neutron;
      GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ neutron_password }}';
      GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ neutron_password }}';
      FLUSH PRIVILEGES;
      EOF
    executable: /bin/bash
  changed_when: false

- name: Configure service
  ansible.builtin.include_tasks:
    file: configure_service.yml

- name: Configure Neutron
  ansible.builtin.include_tasks:
    file: configure_neutron.yml

- name: Configure ML2
  ansible.builtin.include_tasks:
    file: configure_ml2.yml

# - name: Setup configuration
#   ansible.builtin.include_tasks:
#     file: configure.yml
