---
- name: Install Neutron package
  ansible.builtin.package:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-openvswitch-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: present

- name: Reconfigure neutron.conf - set MySQL MariaDB connection database
  ansible.builtin.replace:
    path: /etc/neutron/neutron.conf
    regexp: "^\\[database\\](\n(.*))*?\n*(# From neutron.db).*"
    replace: "{{ lookup('ansible.builtin.template', 'database.conf.j2') }}"

- name: Reconfigure neutron.conf - set Keystone authtoken
  ansible.builtin.replace:
    path: /etc/neutron/neutron.conf
    regexp: "^\\[keystone_authtoken\\](\n(.*))*?\n*(# From keystonemiddleware.auth_token).*"
    replace: "{{ lookup('ansible.builtin.template', 'keystone_authtoken.conf.j2') }}"
