---
- name: Reconfigure ml2_conf.ini - set ml2
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.template', 'ml2.conf.j2') }}"

- name: Reconfigure ml2_conf.ini - set ml2_type_flat
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2_type_flat\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.template', 'ml2_type_flat.conf.j2') }}"

- name: Reconfigure dhcp_agent.ini - set dhcp agent default
  ansible.builtin.replace:
    path: /etc/neutron/dhcp_agent.ini
    regexp: "^\\[DEFAULT\\](\n(.*))*?\n*(# From neutron.base.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'dhcp_agent_default.conf.j2') }}"

- name: Reconfigure metadata_agent.ini - set metadata default
  ansible.builtin.replace:
    path: /etc/neutron/metadata_agent.ini
    regexp: "^\\[DEFAULT\\](\n(.*))*?\n*(# From neutron.metadata.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'metadata_default.conf.j2') }}"
