---
- name: Reconfigure l3_agent.ini - set default
  ansible.builtin.replace:
    path: /etc/neutron/l3_agent.ini
    regexp: "^\\[DEFAULT\\](\n(.*))*?\n*(# From neutron.base.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'l3_agent_default.conf.j2') }}"
