---
- name: Get selected CNI plugin
  ansible.builtin.set_fact:
    selected_cni_plugin: "{{ lookup('ansible.utils.index_of', cni_networking_plugins, 'eq', cni_selected_netplugin, 'name') }}"

- name: Set basic CNI networking config
  ansible.builtin.copy:
    src: "{{ plugin.path }}"
    dest: "{{ plugin.dest }}"
    mode: "644"
  vars:
    plugin: "{{ cni_networking_plugins[selected_cni_plugin | int] }}"
  when: plugin.name == 'basic'

- name: Set Calico CNI networking plugin
  ansible.builtin.command:
    cmd: kubectl apply -f {{ plugin.path }}
  become: false
  vars:
    plugin: "{{ cni_networking_plugins[selected_cni_plugin | int] }}"
  when: plugin.name == 'calico'
  changed_when: false
