---
- name: Initialize database
  ansible.builtin.shell:
    cmd: |
      mysql -u root <<EOF
      CREATE DATABASE IF NOT EXISTS nova_api;
      CREATE DATABASE IF NOT EXISTS nova;
      CREATE DATABASE IF NOT EXISTS nova_cell0;
      GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost' IDENTIFIED BY '{{ nova_password }}';
      GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%' IDENTIFIED BY '{{ nova_password }}';
      GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '{{ nova_password }}';
      GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '{{ nova_password }}';
      GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'localhost' IDENTIFIED BY '{{ nova_password }}';
      GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'%' IDENTIFIED BY '{{ nova_password }}';
      FLUSH PRIVILEGES;
      EOF
    executable: /bin/bash
  changed_when: false

- name: Configure service
  ansible.builtin.include_tasks:
    file: configure_service.yml

- name: Install Nova package
  ansible.builtin.package:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: present

- name: Setup configuration
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Populate the nova-api database
  ansible.builtin.command:
    cmd: sudo -u nova nova-manage api_db sync
  changed_when: false

- name: Register the cell0 database
  ansible.builtin.command:
    cmd: sudo -u nova nova-manage cell_v2 map_cell0
  register: register_cell0
  changed_when: register_cell0.stdout is defined and "is already setup" not in register_cell0.stdout

- name: Create the cell1 cell
  ansible.builtin.command:
    cmd: sudo -u nova nova-manage cell_v2 create_cell --name=cell1
  register: create_cell1
  changed_when: create_cell1.stdout is defined and "combination already exists" not in create_cell1.stdout
  failed_when: create_cell1.rc != 0 and "combination already exists" not in create_cell1.stdout

- name: Populate the nova database
  ansible.builtin.command:
    cmd: sudo -u nova nova-manage db sync
  changed_when: false

- name: Start and enable Nova API
  ansible.builtin.service:
    name: nova-api
    state: restarted
    enabled: true

- name: Start and enable Nova scheduler
  ansible.builtin.service:
    name: nova-scheduler
    state: restarted
    enabled: true

- name: Start and enable Nova conductor
  ansible.builtin.service:
    name: nova-conductor
    state: restarted
    enabled: true

- name: Start and enable Nova novncproxy
  ansible.builtin.service:
    name: nova-novncproxy
    state: restarted
    enabled: true
