---
- name: Install Neutron package
  ansible.builtin.package:
    name:
      - neutron-openvswitch-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: present

- name: Configure Neutron
  ansible.builtin.include_tasks:
    file: configure_neutron.yml

- name: Configure OpenVSwitch
  ansible.builtin.include_tasks:
    file: configure_openvswitch.yml

- name: Reconfigure Nova - set neutron
  ansible.builtin.replace:
    path: /etc/nova/nova.conf
    regexp: "^\\[neutron\\](\n(.*))*?\n*(# Configuration options for neutron).*"
    replace: "{{ lookup('ansible.builtin.template', 'nova_neutron.conf.j2') }}"

- name: Add br-prvdr
  ansible.builtin.shell:
    cmd: |
      ovs-vsctl add-br br-prvdr
      ovs-vsctl add-port br-prvdr {{ provider_interface }}
    executable: /bin/bash
  register: add_br_prvdr
  failed_when: >
    add_br_prvdr.stderr is defined and add_br_prvdr.stderr != ""
    and "already exists" is not in add_br_prvdr.stderr
  changed_when: add_br_prvdr.rc == 0 and add_br_prvdr.stderr is defined and add_br_prvdr.stderr == ""

- name: Re-configure provider interface
  ansible.builtin.template:
    src: interface.yml.j2
    dest: /etc/netplan/50-vagrant.yaml
    mode: "640"
  register: configure_provider_if

- name: Netplan apply
  ansible.builtin.command:
    cmd: netplan apply
  when: configure_provider_if.changed is defined and configure_provider_if.changed
  changed_when: false

- name: Start and enable Neutron OVS agent
  ansible.builtin.service:
    name: neutron-openvswitch-agent
    state: restarted
    enabled: true
