---
lab:
  vars:
    root_dir: "{{ lookup('ansible.builtin.env', 'ROOT_DIR') }}"
    target_env: local
    provider_interface: eth1
  children:
    controller:
      hosts:
        controller01:
          ansible_host: "{{ controller01.mgmtnet_ip_address }}"
    compute:
      hosts:
        compute01:
          ansible_host: "{{ compute01.mgmtnet_ip_address }}"
        compute02:
          ansible_host: "{{ compute02.mgmtnet_ip_address }}"
    storage:
      hosts:
        storage01:
          ansible_host: "{{ storage01.mgmtnet_ip_address }}"
