---
- name: Initialize database
  ansible.builtin.shell:
    cmd: |
      mysql -u root <<EOF
      CREATE DATABASE IF NOT EXISTS placement;
      GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'localhost' IDENTIFIED BY '{{ placement_password }}';
      GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'%' IDENTIFIED BY '{{ placement_password }}';
      FLUSH PRIVILEGES;
      EOF
    executable: /bin/bash
  changed_when: false

- name: Configure service
  ansible.builtin.include_tasks:
    file: configure_service.yml

- name: Install Placement package
  ansible.builtin.package:
    name: placement-api
    state: present

- name: Setup configuration
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Populate the placement database
  ansible.builtin.command:
    cmd: sudo -u placement placement-manage db sync
  changed_when: false

- name: Start and enable Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true
