---
- name: Deploy and setup OpenStack on compute node
  hosts: compute
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: nova_compute
    - role: neutron_compute
