---
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: install_dependencies.yml

- name: Ensure the directory of /usr/lib/systemd/system/jenkins.service.d exists
  ansible.builtin.file:
    path: /usr/lib/systemd/system/jenkins.service.d
    mode: "775"
    state: directory

- name: Create jenkins.conf file
  ansible.builtin.template:
    src: jenkins.conf.j2
    dest: /usr/lib/systemd/system/jenkins.service.d/jenkins.conf
    mode: "644"

- name: Ensure the directory of /var/lib/jenkins/init.groovy.d exists
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    mode: "755"
    state: directory

- name: Create .groovy file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /var/lib/jenkins/init.groovy.d/{{ item }}
    mode: "644"
  loop:
    - basic-security.groovy
    - plugins.groovy
  loop_control:
    label: "{{ item }}"

- name: Enable and start Jenkins services
  ansible.builtin.systemd_service:
    name: jenkins
    enabled: true
    state: restarted
    daemon_reload: true
