---
mariadb_password: vagrant
keystone_password: vagrant
glance_password: vagrant
os_glance_password: vagrant
placement_password: vagrant
nova_password: vagrant
neutron_password: vagrant
os_neutron_password: vagrant
