---
- name: Reconfigure ml2_conf.ini - set ml2
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.file', 'ml2.conf') }}"

- name: Reconfigure ml2_conf.ini - set ml2_type_flat
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2_type_flat\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.file', 'ml2_type_flat.conf') }}"

- name: Reconfigure ml2_conf.ini - set ml2_type_vxlan
  ansible.builtin.replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: "^\\[ml2_type_vxlan\\](\n(.*))*?\n*(# From neutron.ml2).*"
    replace: "{{ lookup('ansible.builtin.file', 'ml2_type_vxlan.conf') }}"
