---
- name: Reconfigure neutron.conf - set MySQL MariaDB connection database
  ansible.builtin.replace:
    path: /etc/neutron/neutron.conf
    regexp: "^\\[database\\](\n(.*))*?\n*(# From neutron.db).*"
    replace: "{{ lookup('ansible.builtin.template', 'database.conf.j2') }}"

- name: Reconfigure neutron.conf - set Keystone authtoken
  ansible.builtin.replace:
    path: /etc/neutron/neutron.conf
    regexp: "^\\[keystone_authtoken\\](\n(.*))*?\n*(# From keystonemiddleware.auth_token).*"
    replace: "{{ lookup('ansible.builtin.template', 'keystone_authtoken.conf.j2') }}"

- name: Reconfigure dhcp_agent.ini - set dhcp agent default
  ansible.builtin.replace:
    path: /etc/neutron/dhcp_agent.ini
    regexp: "^\\[DEFAULT\\](\n(.*))*?\n*(# From neutron.base.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'dhcp_agent_default.conf.j2') }}"

- name: Reconfigure metadata_agent.ini - set metadata default
  ansible.builtin.replace:
    path: /etc/neutron/metadata_agent.ini
    regexp: "^\\[DEFAULT\\](\n(.*))*?\n*(# From neutron.metadata.agent).*"
    replace: "{{ lookup('ansible.builtin.template', 'metadata_default.conf.j2') }}"
