---
- name: Change root password
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      gitlab-rails console << EOF
      user = User.find_by_username '{{ gitlab_root_username }}'
      user.password = '{{ gitlab_root_password }}'
      user.password_confirmation = '{{ gitlab_root_password }}'
      user.save!
      EOF
    executable: /bin/bash
  register: change_root_password
  changed_when: '"true" in change_root_password.stdout'
  failed_when: >
    "false" in change_root_password.stdout or "ERROR" in change_root_password.stdout or "error" in change_root_password.stdout or
    (change_root_password.stderr is defined and change_root_password.stderr != "" and change_root_password.rc != 0)

- name: Create root PAT
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      gitlab-rails console << EOF
      user = User.find_by_username '{{ gitlab_root_username }}'
      token = user.personal_access_tokens.create(
        scopes: ['api', 'read_user', 'read_repository', 'write_repository', 'create_runner', 'manage_runner', 'sudo'],
        name: 'Automation token for root',
        expires_at: 365.days.from_now)
      token.set_token('{{ gitlab_root_token }}')
      token.save!
      EOF
    executable: /bin/bash
  register: create_root_pat
  changed_when: '"true" in create_root_pat.stdout and "duplicate key value" not in create_root_pat.stdout'
  failed_when: >
    "false" in create_root_pat.stdout or
    (("ERROR" in create_root_pat.stdout or "error" in create_root_pat.stdout) and "duplicate key value" not in create_root_pat.stdout) or
    (create_root_pat.stderr is defined and create_root_pat.stderr != "" and create_root_pat.rc != 0)

- name: Create standard user
  ansible.builtin.uri:
    url: "{{ gitlab_api_url }}/users"
    method: POST
    headers:
      Authorization: Bearer {{ gitlab_root_token }}
    body:
      username: "{{ gitlab_user_username }}"
      name: "{{ gitlab_user_name }}"
      email: "{{ gitlab_user_email }}"
      password: "{{ gitlab_user_password }}"
      skip_confirmation: true
    body_format: json
    validate_certs: false
  register: create_standard_user
  changed_when: create_standard_user.json.id is defined
  failed_when: >
    (create_standard_user.status != 200 and create_standard_user.status != 201 and
    create_standard_user.json.message is defined and "has already been taken" not in create_standard_user.json.message) or
    (create_standard_user.msg is defined and "Connection refused" in create_standard_user.msg)
