---
- name: Pre-setup
  ansible.builtin.import_playbook: playbook_pre_setup.yml

- name: Setup Gitlab
  ansible.builtin.import_playbook: playbook_setup_gitlab.yml

- name: Setup Jenkins
  ansible.builtin.import_playbook: playbook_setup_jenkins.yml

- name: Setup Runner
  ansible.builtin.import_playbook: playbook_setup_runner.yml
