---
- name: Download Containerd archive to localhost
  ansible.builtin.get_url:
    url: "{{ containerd_download_url }}"
    dest: /tmp/{{ containerd_download_url | basename }}
    mode: "644"
  become: false
  delegate_to: localhost
  run_once: true

- name: Upload Containerd and extract
  ansible.builtin.unarchive:
    src: /tmp/{{ containerd_download_url | basename }}
    dest: /usr/local/bin
    extra_opts: ["--strip-components=1", "--show-stored-names"]

- name: Ensure the directory /etc/containerd exists
  ansible.builtin.file:
    path: /etc/containerd
    mode: "755"
    state: directory

- name: Set Containerd configuration
  ansible.builtin.copy:
    src: containerd.config.toml
    dest: /etc/containerd/config.toml
    mode: "644"

- name: Create the Containerd systemd service file
  ansible.builtin.copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: "644"
