---
- name: Download Runc
  ansible.builtin.get_url:
    url: "{{ runc_download_url }}"
    dest: /home/{{ ansible_user }}/
    mode: "755"
    force: true

- name: Install Runc
  ansible.builtin.command:
    chdir: /home/{{ ansible_user }}
    cmd: install -m 755 {{ runc_download_url | basename }} /usr/local/sbin/runc
  register: runc
  changed_when: false

- name: Ensure the directory /opt/cni/bin exists
  ansible.builtin.file:
    path: /opt/cni/bin
    mode: "755"
    state: directory

- name: Download CNI plugins archive to localhost
  ansible.builtin.get_url:
    url: "{{ cni_plugin_download_url }}"
    dest: /tmp/{{ cni_plugin_download_url | basename }}
    mode: "644"
  become: false
  delegate_to: localhost
  run_once: true

- name: Upload CNI plugins and extract
  ansible.builtin.unarchive:
    src: /tmp/{{ cni_plugin_download_url | basename }}
    dest: /opt/cni/bin
    extra_opts: ["--strip-components=1", "--show-stored-names"]
