---
- name: Download containerd and extract
  ansible.builtin.unarchive:
    src: "{{ containerd_download_url }}"
    remote_src: true
    dest: /usr/local/bin
    extra_opts: ["--strip-components=1", "--show-stored-names"]

- name: Ensure the directory /etc/containerd exists
  ansible.builtin.file:
    path: /etc/containerd
    mode: "755"
    state: directory

- name: Set Containerd configuration
  ansible.builtin.copy:
    src: containerd.config.toml
    dest: /etc/containerd/config.toml
    mode: "644"

- name: Create the Containerd systemd service file
  ansible.builtin.copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: "644"

- name: Restart containerd service
  ansible.builtin.systemd_service:
    name: containerd
    enabled: true
    state: restarted
    daemon_reload: true
