---
- name: Deploy and setup OpenStack on controller node
  hosts: controller
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: controller
    - role: keystone
    - role: glance
    - role: placement
    - role: nova_controller
    - role: neutron_controller
    - role: horizon
    - role: cinder_controller
