---
- name: Deploy and setup OpenStack on controller
  hosts: controller
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: controller
