---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

ntp_server: time.aws.com

gitlab_ce_install_script: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh

gitlab_user_email: vagrant@examplemaildomain.com
gitlab_user_name: Vagrant

gitlab_base_url: http://{{ ansible_host }}
gitlab_api_url: "{{ gitlab_base_url }}/api/v4"
