---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

cicd_list: "{{ (lookup('file', root_dir ~ '/ansible/shared_resources/inventories/' ~ target_env ~ '/cicd.yml') | from_yaml) }}"

arch_mapping:
  x86_64: amd64
  aarch64: arm64

ntp_server: time.aws.com

gitlab_ce_install_script: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh

gitlab_user_email: vagrant@examplemaildomain.com
gitlab_user_name: Vagrant

gitlab_base_url: http://{{ hostvars[cicd_list.gitlab01.name].ansible_host }}
gitlab_api_url: "{{ gitlab_base_url }}/api/v4"

gitlab_runner_binary: >
  https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/binaries/gitlab-runner-linux-{{ arch_mapping[ansible_architecture] }}
