---
- name: Install packages dependencies with Snap - classic
  community.general.snap:
    name:
      - node
    classic: true
    state: present

- name: Install Gitlab Runner
  ansible.builtin.include_tasks:
    file: gitlab.yml
  when: '"gitlab" in runner_agent'

- name: Install Jenkins Runner
  ansible.builtin.include_tasks:
    file: jenkins.yml
  when: '"jenkins" in runner_agent'
