---
- name: Install packages dependencies with Snap - classic
  community.general.snap:
    name:
      - node
    classic: true
    state: present

- name: Install gitlab-runner
  ansible.builtin.get_url:
    url: "{{ gitlab_runner_binary }}"
    dest: /usr/local/bin/gitlab-runner
    mode: "755"
    force: true

- name: Gitlab runner creation
  when: hostvars[inventory_hostname].ansible_env.gitlab_runner_token is not defined
  block:
    - name: Create Gitlab runner instance
      ansible.builtin.uri:
        url: "{{ gitlab_api_url }}/user/runners"
        method: POST
        headers:
          Authorization: Bearer {{ gitlab_root_token }}
        body: |
          {
            "runner_type": "instance_type",
            "run_untagged": true,
            "description": "Created automatically by Ansible"
          }
        body_format: json
        validate_certs: false
      register: create_runner
      changed_when: create_runner.json.id is defined
      failed_when: create_runner.status != 200 and create_runner.status != 201

    - name: Save Gitlab runner token to environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: ^gitlab_runner_token=
        line: gitlab_runner_token="{{ create_runner.json.token }}"
        insertafter: EOF
      when: create_runner.json.token is defined
